-- profiles table
create table public.profiles (
  id uuid references auth.users on delete cascade primary key,
  email text not null,
  display_name text,
  locale text default 'ko',
  created_at timestamptz default now()
);

-- beans table (all columns from the plan)
create table public.beans (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  name text not null,
  roastery text not null,
  bean_type text not null check (bean_type in ('single_origin', 'blend')),
  origin_country text,
  origin_country_id bigint,
  origin_region text,
  origin_region_id bigint,
  origin_subregions text[] not null default '{}',
  origin_lat numeric,
  origin_lng numeric,
  farm_producer text,
  origin_entity_id bigint,
  varietal text,
  process_method text not null check (process_method in ('washed', 'natural', 'honey', 'anaerobic', 'carbonic', 'decaf', 'other')),
  process_detail text,
  altitude_m integer,
  harvest_year integer,
  roast_level text not null check (roast_level in ('light', 'medium', 'dark')),
  roast_date date,
  consumed_at timestamptz not null default now(),
  place_type text not null check (place_type in ('cafe', 'home')),
  cafe_name text,
  cafe_location text,
  menu_name text,
  overall_score numeric(3,1) not null check (overall_score >= 1 and overall_score <= 10),
  note text not null default '',
  score_aroma integer check (score_aroma >= 1 and score_aroma <= 5),
  score_acidity integer check (score_acidity >= 1 and score_acidity <= 5),
  score_body integer check (score_body >= 1 and score_body <= 5),
  score_sweetness integer check (score_sweetness >= 1 and score_sweetness <= 5),
  score_aftertaste integer check (score_aftertaste >= 1 and score_aftertaste <= 5),
  score_balance integer check (score_balance >= 1 and score_balance <= 5),
  purchase_source text check (purchase_source in ('online', 'roastery', 'cafe', 'other')),
  price integer,
  weight_g integer,
  purchased_at date,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- tasting_tags table
create table public.tasting_tags (
  id uuid default gen_random_uuid() primary key,
  bean_id uuid references public.beans(id) on delete cascade not null,
  user_id uuid references public.profiles(id) on delete cascade not null,
  tag text not null,
  category text not null default 'other'
);

-- origin_presets table
create table public.origin_presets (
  id serial primary key,
  country text not null,
  region text not null,
  lat numeric,
  lng numeric,
  altitude_range text,
  signature text,
  key_varietals text[],
  name_ko text,
  name_en text
);

-- Normalized catalog for country → region → farm/producer input suggestions.
-- Data is seeded by migration 00008_origin_catalog.sql.
create table public.origin_countries (
  id bigint generated by default as identity primary key,
  source_key text not null unique,
  name_en text not null unique,
  name_ko text,
  created_at timestamptz not null default now()
);

create table public.origin_regions (
  id bigint generated by default as identity primary key,
  source_key text not null unique,
  country_id bigint not null references public.origin_countries(id) on delete cascade,
  name text not null,
  name_ko text,
  part_1 text,
  part_1_ko text,
  part_2 text,
  part_2_ko text,
  part_3 text,
  part_3_ko text,
  canonical_region_id bigint references public.origin_regions(id) on delete set null,
  display_name text,
  display_name_ko text,
  is_canonical boolean not null default false,
  created_at timestamptz not null default now(),
  unique (country_id, name)
);

create table public.origin_entities (
  id bigint generated by default as identity primary key,
  source_key text not null unique,
  country_id bigint not null references public.origin_countries(id) on delete cascade,
  region_id bigint references public.origin_regions(id) on delete set null,
  name text not null,
  name_ko text,
  entity_type text,
  farm_name text,
  farm_name_ko text,
  producer_name text,
  producer_name_ko text,
  owner_name text,
  owner_name_ko text,
  mill_name text,
  mill_name_ko text,
  source_datasets text,
  created_at timestamptz not null default now()
);

alter table public.beans
  add constraint beans_origin_country_id_fkey
    foreign key (origin_country_id) references public.origin_countries(id) on delete set null,
  add constraint beans_origin_region_id_fkey
    foreign key (origin_region_id) references public.origin_regions(id) on delete set null,
  add constraint beans_origin_entity_id_fkey
    foreign key (origin_entity_id) references public.origin_entities(id) on delete set null;

create table public.blend_components (
  id uuid default gen_random_uuid() primary key,
  bean_id uuid not null references public.beans(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  origin_country text not null,
  origin_region text,
  origin_subregions text[] not null default '{}',
  farm_producer text,
  varietal text,
  process_method text check (process_method in ('washed', 'natural', 'honey', 'anaerobic', 'carbonic', 'decaf', 'other')),
  process_detail text,
  percentage numeric(5,2) not null check (percentage > 0 and percentage <= 100),
  sort_order integer not null default 0,
  created_at timestamptz default now()
);

-- Indexes
create index idx_beans_user_id on public.beans(user_id);
create index idx_beans_consumed_at on public.beans(consumed_at desc);
create index idx_beans_origin_country on public.beans(origin_country);
create index idx_beans_origin_country_id on public.beans(origin_country_id);
create index idx_beans_origin_region_id on public.beans(origin_region_id);
create index idx_beans_origin_entity_id on public.beans(origin_entity_id);
create index idx_beans_process_method on public.beans(process_method);
create index idx_tasting_tags_bean_id on public.tasting_tags(bean_id);
create index idx_tasting_tags_user_id on public.tasting_tags(user_id);
create index idx_origin_regions_country on public.origin_regions(country_id, name);
create index idx_origin_regions_canonical_lookup on public.origin_regions(country_id, canonical_region_id);
create index idx_origin_entities_country_region on public.origin_entities(country_id, region_id, name);
create index idx_blend_components_bean_id on public.blend_components(bean_id);
create index idx_blend_components_user_id on public.blend_components(user_id);

-- RLS
alter table public.profiles enable row level security;
alter table public.beans enable row level security;
alter table public.tasting_tags enable row level security;
alter table public.origin_presets enable row level security;
alter table public.origin_countries enable row level security;
alter table public.origin_regions enable row level security;
alter table public.origin_entities enable row level security;
alter table public.blend_components enable row level security;

-- profiles: user can read/update own
create policy "Users can view own profile" on public.profiles for select using (auth.uid() = id);
create policy "Users can update own profile" on public.profiles for update using (auth.uid() = id);

-- beans: user CRUD own
create policy "Users can view own beans" on public.beans for select using (auth.uid() = user_id);
create policy "Users can insert own beans" on public.beans for insert with check (auth.uid() = user_id);
create policy "Users can update own beans" on public.beans for update using (auth.uid() = user_id);
create policy "Users can delete own beans" on public.beans for delete using (auth.uid() = user_id);

-- tasting_tags: user CRUD own
create policy "Users can view own tags" on public.tasting_tags for select using (auth.uid() = user_id);
create policy "Users can insert own tags" on public.tasting_tags for insert with check (auth.uid() = user_id);
create policy "Users can delete own tags" on public.tasting_tags for delete using (auth.uid() = user_id);

-- Origin catalogs: authenticated users can read suggestions, but never write them.
create policy "Authenticated users can read presets" on public.origin_presets for select to authenticated using (true);
create policy "Authenticated users can read origin countries" on public.origin_countries for select to authenticated using (true);
create policy "Authenticated users can read origin regions" on public.origin_regions for select to authenticated using (true);
create policy "Authenticated users can read origin entities" on public.origin_entities for select to authenticated using (true);

-- Blend components: strictly owned by the record's user.
create policy "Users can view own blend components" on public.blend_components for select using (auth.uid() = user_id);
create policy "Users can insert own blend components" on public.blend_components for insert with check (auth.uid() = user_id);
create policy "Users can update own blend components" on public.blend_components for update using (auth.uid() = user_id);
create policy "Users can delete own blend components" on public.blend_components for delete using (auth.uid() = user_id);

-- updated_at trigger
create or replace function update_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger set_beans_updated_at
  before update on public.beans
  for each row execute function update_updated_at();
