FROM sha256:6d212262bcd9caa11bafa4a6a01787bcdd42163ba517ee5dc340a46f869005d4
COPY --chown=0:0 auth-security-p3 /usr/local/bin/auth
LABEL site.beanmap.security.auth.version="v2.195.0-go1.26.6-p3" \
      site.beanmap.security.auth.crypto="v0.56.0" \
      site.beanmap.security.auth.chi="v5.3.0" \
      site.beanmap.security.auth.grpc="v1.83.1"
