-- Disposable database only: each DDL owner's new objects must already be
-- private before RLS is enabled. Everything created here is rolled back.
begin;
grant create on schema public to postgres, supabase_admin;
set local role postgres;
create table public.ddl_postgres_table_canary(id bigint generated by default as identity, payload text);
create sequence public.ddl_postgres_sequence_canary;
reset role;
set local role supabase_admin;
create table public.ddl_admin_table_canary(id bigint generated by default as identity, payload text);
create sequence public.ddl_admin_sequence_canary;
reset role;
do $$
declare item record; role_name text;
begin
  for item in select c.oid,c.relname,c.relkind,c.relacl,c.relowner
    from pg_class c join pg_namespace n on n.oid=c.relnamespace
    where n.nspname='public' and c.relname like 'ddl_%canary%'
  loop
    if exists (select 1 from aclexplode(coalesce(item.relacl,
      acldefault(case when item.relkind='S' then 's'::"char" else 'r'::"char" end,item.relowner)))
      where grantee=0) then raise exception 'PUBLIC implicitly receives %',item.relname; end if;
    foreach role_name in array array['anon','authenticated','service_role','authenticator','beanmap_api','beanlog_api','beanmap_api_runtime'] loop
      if to_regrole(role_name) is null then continue; end if;
      if item.relkind='S' then
        if has_sequence_privilege(role_name,item.oid,'USAGE,SELECT,UPDATE') then raise exception '% implicitly receives sequence %',role_name,item.relname; end if;
      elsif has_table_privilege(role_name,item.oid,'SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER') then
        raise exception '% implicitly receives table %',role_name,item.relname;
      end if;
    end loop;
  end loop;
end;
$$;
-- Owner writes and both explicit/identity sequence allocation still work.
set local role postgres;
insert into public.ddl_postgres_table_canary(payload) values ('owner');
select nextval('public.ddl_postgres_sequence_canary');
reset role;
set local role supabase_admin;
insert into public.ddl_admin_table_canary(payload) values ('owner');
select nextval('public.ddl_admin_sequence_canary');
reset role;
rollback;

-- Optional net fixture or installed extension: inspect privileges only, never
-- invoke HTTP or worker-control routines or enqueue a network request.
do $$
declare role_name text; item record;
begin
  if to_regnamespace('net') is null then return; end if;
  foreach role_name in array array['anon','authenticated','service_role','authenticator','beanmap_api','beanlog_api','beanmap_api_runtime'] loop
    if to_regrole(role_name) is null then continue; end if;
    if has_schema_privilege(role_name,'net','USAGE,CREATE') then raise exception '% can use network schema',role_name; end if;
    for item in select p.oid from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='net' loop
      if has_function_privilege(role_name,item.oid,'EXECUTE') then raise exception '% can execute network routine',role_name; end if;
    end loop;
    for item in select c.oid,c.relkind from pg_class c join pg_namespace n on n.oid=c.relnamespace
      where n.nspname='net' and c.relkind in ('r','p','S')
    loop
      if item.relkind='S' then
        if has_sequence_privilege(role_name,item.oid,'USAGE,SELECT,UPDATE') then raise exception 'Network sequence exposed'; end if;
      elsif has_table_privilege(role_name,item.oid,'SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER') then raise exception 'Network table exposed'; end if;
    end loop;
  end loop;
end;
$$;
