import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const require=createRequire('/usr/src/app/package.json');
assert.equal(require('fastify/package.json').version,'5.12.3');
assert.equal(require('find-my-way/package.json').version,'9.9.0');
const fastify=require('fastify')();
fastify.post('/validation',{schema:{body:{content:{'application/json':{schema:{type:'object',required:['required'],properties:{required:{type:'string'}},additionalProperties:false}}}}}},async()=>({accepted:true}));
assert.equal((await fastify.inject({method:'POST',url:'/validation',headers:{'content-type':'application/json'},payload:{required:'ok'}})).statusCode,200);
for(const [type,status] of [['application/json',400],['application/json\ta',415]])assert.equal((await fastify.inject({method:'POST',url:'/validation',headers:{'content-type':type},payload:'{}'})).statusCode,status);
await fastify.close();
const router=require('find-my-way')();router.on('GET','/',()=>{});
for(const method of ['constructor','toString','__proto__'])assert.equal(router.find(method,'/'),null);
const {build}=await import('/usr/src/app/dist/server/app.js');
const {build:buildAdmin}=await import('/usr/src/app/dist/server/admin-app.js');
const app=build(),admin=buildAdmin();await app.ready();await admin.ready();
assert.equal((await app.inject('/health')).statusCode,200);assert.equal((await app.inject('/')).statusCode,200);
assert.equal((await app.inject('/no-such-fixture-route')).statusCode,404);
assert.equal((await admin.inject('/metrics')).statusCode,200);
const spec=app.swagger();assert(Object.keys(spec.paths).length>20);
console.log(JSON.stringify({result:'PASS',fastify:'5.12.3',router:'9.9.0',registeredPaths:Object.keys(spec.paths).length,validationBypass:'blocked',prototypeMethods:'safe',health:200,metrics:200}));
await app.close();await admin.close();
