const ko = {
  eyebrow: "beanmap 운영",
  title: "서비스 관리",
  description: "이용 현황을 확인하고, 원두 입력에 쓰이는 산지 한글 표기를 관리합니다.",
  back: "설정으로 돌아가기",
  link: "관리자 페이지",
  deniedTitle: "관리자 권한이 필요합니다",
  deniedDescription: "운영자로 지정된 계정만 이 페이지를 사용할 수 있습니다.",
  unavailable: "관리 화면을 불러오지 못했습니다",
  unavailableHelp: "잠시 후 다시 시도해 주세요. 연결 상태가 복구되면 최신 정보를 확인할 수 있습니다.",
  retry: "다시 시도",
  overview: "이용 현황",
  users: "전체 가입자",
  beans: "전체 원두 기록",
  new_users_30d: "최근 30일 가입자",
  new_beans_30d: "최근 30일 새 기록",
  active_users_30d: "최근 30일 기록한 사용자",
  periodHelp: "최근 30일은 저장 시각 기준입니다. 탈퇴한 계정과 삭제한 기록은 집계에서 제외됩니다.",
  catalog: "산지 표기 관리",
  catalogHelp: "기록 작성 화면의 추천 목록에 반영됩니다. 공개 산지 소개글은 별도로 관리합니다.",
  country: "국가",
  region: "지역",
  entity: "농장·생산자",
  kind: "분류",
  search: "산지 검색",
  searchPlaceholder: "원문 또는 한글 표기",
  searchButton: "검색",
  name: "원문 이름",
  nameKo: "한글 표기",
  emptyName: "미등록",
  empty: "검색 결과가 없습니다. 검색어나 분류를 바꿔 보세요.",
  edit: "수정",
  editing: "표기 수정",
  reason: "변경 사유",
  reasonPlaceholder: "예: 생산자 공식 표기에 맞춤",
  editHelp: "빈칸으로 저장하면 원문 이름이 표시됩니다. 이미 작성된 개인 기록에는 영향을 주지 않습니다.",
  save: "저장",
  saving: "저장 중…",
  cancel: "취소",
  saved: "저장했습니다.",
  conflict: "다른 관리자가 먼저 수정했습니다. 최신 내용을 불러온 뒤 다시 수정해 주세요.",
  forbidden: "관리자 권한을 확인할 수 없습니다. 다시 로그인하거나 운영자에게 확인해 주세요.",
  invalid: "한글 표기는 120자 이내, 변경 사유는 3~300자로 입력해 주세요.",
  saveError: "저장하지 못했습니다. 입력한 내용은 유지됩니다. 잠시 후 다시 시도해 주세요.",
  missing: "이 항목을 찾을 수 없습니다. 최신 목록을 다시 불러와 주세요.",
  reload: "최신 목록 불러오기",
  previous: "이전",
  next: "다음",
  results: "검색 결과",
  count: "건",
  audit: "최근 변경 이력",
  auditHelp: "최근 30건의 표기 변경과 사유를 보여줍니다.",
  noAudit: "아직 변경 이력이 없습니다.",
  changedAt: "변경 시각",
  before: "변경 전",
  after: "변경 후",
  privacy: "이 화면에는 이용자의 이메일이나 개인 테이스팅 노트가 표시되지 않습니다.",
};

const en: Record<keyof typeof ko, string> = {
  eyebrow: "beanmap operations", title: "Service management",
  description: "Review usage and maintain Korean origin labels in the record form.",
  back: "Back to settings", link: "Admin console",
  deniedTitle: "Administrator access required",
  deniedDescription: "This page is available to designated operators only.",
  unavailable: "Unable to load the admin console",
  unavailableHelp: "Please try again shortly to load the latest information.",
  retry: "Try again", overview: "Usage overview", users: "Total users", beans: "Total records",
  new_users_30d: "New users · 30 days", new_beans_30d: "New records · 30 days",
  active_users_30d: "Users who recorded · 30 days",
  periodHelp: "The last 30 days use creation time. Deleted accounts and records are excluded.",
  catalog: "Origin labels",
  catalogHelp: "Changes appear in record-form suggestions. Public origin guides are maintained separately.",
  country: "Country", region: "Region", entity: "Farm / producer", kind: "Category",
  search: "Search origins", searchPlaceholder: "Original or Korean name", searchButton: "Search",
  name: "Original name", nameKo: "Korean label", emptyName: "Not set",
  empty: "No results. Try another search or category.", edit: "Edit", editing: "Edit label",
  reason: "Reason for change", reasonPlaceholder: "For example: match the producer’s official spelling",
  editHelp: "Leave blank to display the original name. Existing personal records are unaffected.",
  save: "Save", saving: "Saving…", cancel: "Cancel", saved: "Saved.",
  conflict: "Another administrator changed this label. Load the latest version before editing again.",
  forbidden: "Administrator access could not be verified. Sign in again or contact the operator.",
  invalid: "Use up to 120 characters for the label and 3–300 characters for the reason.",
  saveError: "Could not save. Your input is preserved. Please try again shortly.",
  missing: "This item is no longer available. Reload the latest list.", reload: "Reload latest list",
  previous: "Previous", next: "Next", results: "Results", count: "items",
  audit: "Recent changes", auditHelp: "The latest 30 label changes and their reasons.",
  noAudit: "No changes yet.", changedAt: "Changed at", before: "Before", after: "After",
  privacy: "User email addresses and personal tasting notes are not displayed here.",
};

export function adminCopy(locale: string) { return locale === "en" ? en : ko; }
